function prepareMeeting(id){currentMeetingId=id;let m=getMeeting(id),s=getStudent(m.studentId),g=getGuardian(m.guardianId),t=getTeacher(m.teacherId);showView("live");$("liveTitle").textContent="Preparar reunión";$("liveSubtitle").textContent=`${m.date} · ${m.startTime} · ${m.modality}`;$("prepInfo").innerHTML=`<div class="grid two"><div><b>Estudiante</b><p>${s.name}<br>${s.course} · ${s.code}</p></div><div><b>Representante</b><p>${g.name} · ${g.relation}<br>${g.email} · ${g.phone}</p></div></div><p><b>Docente:</b> ${t.name}<br><b>Motivo:</b> ${m.reason}</p><span class="tag green">Datos sincronizados desde Runachay ✓</span>`;$("participantArea").classList.remove("hidden");let parts=[["Madre",g.name],["Padre","Padre / representante"],["Estudiante",s.name],["Docente",t.name],["Coordinador","Coordinador"],["DECE","DECE"],["Otro","Otro"]];$("participantCheckboxes").innerHTML=parts.map((p,i)=>`<label style="margin-right:12px"><input class="pcheck" data-role="${p[0]}" data-name="${p[1]}" type="checkbox" ${["Madre","Estudiante","Docente"].includes(p[0])?"checked":""}> ${p[0]}</label>`).join("");document.querySelectorAll(".pcheck").forEach(c=>c.onchange=renderParticipants);renderParticipants();$("liveRoom").classList.add("hidden");$("prepCard").classList.remove("hidden")}
function renderParticipants(){let arr=[...document.querySelectorAll(".pcheck:checked")];$("participantAvatars").innerHTML=arr.map(c=>`<div class="participant-chip"><div class="avatar sm">${initials(c.dataset.name)}</div><div><b class="small">${c.dataset.name}</b><div class="small muted">${c.dataset.role}</div></div></div>`).join("")}
$("startLiveBtn").onclick=()=>{if(!$("consentCheck").checked){toast("Debes confirmar el consentimiento informado");return}let m=getMeeting(currentMeetingId);m.status="live";save();transcript=[];evidence=[];aiSuggestions=[];liveIdx=0;timerSec=0;paused=false;$("prepCard").classList.add("hidden");$("liveRoom").classList.remove("hidden");$("liveClock").classList.remove("hidden");timerInt=setInterval(()=>{if(!paused){timerSec++;$("timer").textContent=String(Math.floor(timerSec/60)).padStart(2,"0")+":"+String(timerSec%60).padStart(2,"0")}},1000);buildSpeakerOptions();renderTranscript();renderAI();renderEvidence();renderLiveCommitments();toast("Reunión iniciada")}
function buildSpeakerOptions(){let s=getStudent(getMeeting(currentMeetingId).studentId),g=getGuardian(getMeeting(currentMeetingId).guardianId),t=getTeacher(getMeeting(currentMeetingId).teacherId);$("manualSpeaker").innerHTML=`<option>${t.name}|Docente</option><option>${g.name}|${g.relation}</option><option>${s.name}|Estudiante</option>`}
$("simulateConversation").onclick=()=>{if(paused){toast("Reanuda la reunión primero");return}if(liveIdx>=convo.length){toast("Conversación demo completada");return}let [name,role,text]=convo[liveIdx++];transcript.push({name,role,text,time:new Date().toLocaleTimeString("es-EC",{hour:"2-digit",minute:"2-digit",second:"2-digit"})});$("speakingNow").textContent=name+" está hablando";analyzeLine(text,name,role);renderTranscript();renderAI();renderLiveCommitments()}
$("pauseBtn").onclick=()=>{paused=!paused;$("pauseBtn").textContent=paused?"Reanudar":"Pausar";$("speakingNow").textContent=paused?"Transcripción pausada":"Escuchando…";toast(paused?"Reunión pausada":"Reunión reanudada")}
$("manualAdd").onclick=()=>{let val=$("manualText").value.trim();if(!val)return;let [name,role]=$("manualSpeaker").value.split("|");transcript.push({name,role,text:val,time:new Date().toLocaleTimeString("es-EC")});$("manualText").value="";analyzeLine(val,name,role);renderTranscript();renderAI()}
function renderTranscript(){$("transcriptPanel").innerHTML=transcript.map(x=>`<div class="msg"><div class="avatar sm">${initials(x.name)}</div><div><div><span class="name">${x.name}</span><time>${x.time}</time></div><div class="role">${x.role}</div><div class="txt">${x.text}</div></div></div>`).join("")||`<div class="muted small">Pulsa “Simular conversación” para generar una intervención.</div>`;$("transcriptPanel").scrollTop=$("transcriptPanel").scrollHeight}
function analyzeLine(text,name,role){
 if(/irresponsable/i.test(text)) aiSuggestions.push({type:"subjective",original:"Sofía es irresponsable.",suggested:"Se han identificado entregas incompletas o fuera del plazo establecido durante las últimas semanas.",status:"pending"});
 if(/nunca hace/i.test(text)) aiSuggestions.push({type:"evidence",original:"El estudiante nunca hace las tareas.",suggested:"¿Desea especificar fechas, registros o ejemplos?",status:"pending"});
 if(/rutina diaria|revisar.*agenda|revisaremos diariamente/i.test(text)) aiSuggestions.push({type:"agreement",original:text,suggested:"Establecer una rutina diaria de organización y revisión de agenda.",status:"pending"});
}
function renderAI(){let basic=`<div class="ai-card"><h4>✨ Tema detectado</h4><p>Organización académica</p></div><div class="ai-card"><h4>Situación identificada</h4><p>Dificultades en la gestión del tiempo durante actividades escolares.</p></div>`;let dynamic=aiSuggestions.map((s,i)=>{if(s.status==="discarded")return"";let title=s.type==="subjective"?"⚠️ Lenguaje subjetivo detectado":s.type==="evidence"?"⚠️ Afirmación que puede requerir evidencia":"✨ Posible compromiso detectado";return `<div class="ai-card"><h4>${title}</h4><p><b>Original:</b> ${s.original}</p><p><b>Sugerencia:</b> ${s.suggested}</p><div class="ai-actions">${s.status==="accepted"?'<span class="tag green">Aceptado</span>':`<button class="secondary" onclick="acceptAI(${i})">Aceptar</button><button class="secondary" onclick="editAI(${i})">Editar</button><button class="ghost" onclick="discardAI(${i})">${s.type==="subjective"?"Mantener original":"Descartar"}</button>`}</div></div>`}).join("");$("aiInsights").innerHTML=basic+dynamic}
window.acceptAI=i=>{aiSuggestions[i].status="accepted";if(aiSuggestions[i].type==="agreement"){let s=getStudent(getMeeting(currentMeetingId).studentId);db.commitments.push({id:"c"+(db.commitments.length+1),meetingId:currentMeetingId,responsibleName:s.name,description:"Revisar diariamente su agenda escolar.",dueDate:"2026-08-27",status:"pending"});save()}renderAI();renderLiveCommitments();toast("Sugerencia añadida al acta")}
window.editAI=i=>openModal("Editar sugerencia",`<div class="formgrid"><label class="wide">Texto<textarea id="editSuggestion" rows="4">${aiSuggestions[i].suggested}</textarea></label></div>`,"Guardar",()=>{aiSuggestions[i].suggested=$("editSuggestion").value;aiSuggestions[i].status="accepted";renderAI();toast("Sugerencia editada")})
window.discardAI=i=>{aiSuggestions[i].status="discarded";renderAI();toast("Se mantiene la decisión humana")}
$("addEvidenceBtn").onclick=()=>openModal("Agregar evidencia",`<div class="formgrid"><label>Tipo<select id="evType"><option>Observación</option><option>Documento</option><option>Fotografía</option><option>Correo</option><option>Reporte</option><option>Calificación</option><option>Registro institucional</option></select></label><label>Título<input id="evTitle" value="Reporte académico"></label><label class="wide">Descripción<textarea id="evDesc" rows="3">Evidencia presentada durante la reunión.</textarea></label></div>`,"Agregar",()=>{evidence.push({type:$("evType").value,title:$("evTitle").value,desc:$("evDesc").value});renderEvidence();toast("Evidencia agregada")})
function renderEvidence(){$("evidenceGrid").innerHTML=evidence.map(e=>`<div class="evidence"><div class="icon">📎</div><b>${e.title}</b><small>${e.type}</small><p class="small">${e.desc}</p></div>`).join("")||`<div class="muted small">Aún no hay evidencias registradas.</div>`}
function renderLiveCommitments(){let arr=db.commitments.filter(c=>c.meetingId===currentMeetingId);$("liveCommitments").innerHTML=arr.map(c=>`<div class="ai-card"><h4>${c.responsibleName}</h4><p>${c.description}<br><span class="tag amber">${c.dueDate}</span></p></div>`).join("")||`<div class="muted small">La IA mostrará compromisos detectados.</div>`}
$("finishLiveBtn").onclick=()=>{clearInterval(timerInt);let m=getMeeting(currentMeetingId);m.status="review";save();buildAct();showView("acts");$("processingPanel").classList.remove("hidden");$("actWorkspace").classList.add("hidden");let p=0;let iv=setInterval(()=>{p+=20;$("actProgress").style.width=p+"%";if(p>=100){clearInterval(iv);setTimeout(()=>{$("processingPanel").classList.add("hidden");$("actWorkspace").classList.remove("hidden");renderAct()},350)}},300)}

const sectionNames=["general","antecedentes","temas","evidencias","acuerdos","compromisos","observaciones"];
function buildAct(){let m=getMeeting(currentMeetingId),s=getStudent(m.studentId),g=getGuardian(m.guardianId),t=getTeacher(m.teacherId);let accepted=aiSuggestions.filter(x=>x.status==="accepted");currentAct={meetingId:m.id,number:"ACTA-2026-"+String(184+db.acts.length).padStart(5,"0"),sections:{general:`Fecha: ${m.date}<br>Hora: ${m.startTime}<br>Docente: ${t.name}<br>Estudiante: ${s.name}<br>Representante: ${g.name}<br>Curso: ${s.course}<br>Motivo: ${m.reason}`,antecedentes:"Se realiza la reunión para revisar el proceso de organización académica y establecer acciones de acompañamiento.",temas:"Organización del tiempo, cumplimiento de tareas, acompañamiento familiar y estrategias de seguimiento.",evidencias:evidence.length?evidence.map(e=>e.title+" — "+e.desc).join("<br>"):"No se registraron evidencias adicionales.",acuerdos:accepted.filter(x=>x.type==="agreement").map(x=>x.suggested).join("<br>")||"Establecer una rutina diaria de organización y revisión de agenda.",compromisos:db.commitments.filter(c=>c.meetingId===m.id).map(c=>`${c.responsibleName}: ${c.description} — ${c.dueDate}`).join("<br>")||"Pendiente de validar compromisos.",observaciones:accepted.filter(x=>x.type==="subjective").map(x=>x.suggested).join("<br>")||"Sin observaciones adicionales."}};sectionApproval=Object.fromEntries(sectionNames.map(x=>[x,false]))}
function renderAct(){if(!currentAct){$("actDocument").innerHTML='<div class="muted">No hay acta activa.</div>';return}$("actDocument").innerHTML=`<h2>ACTA DE REUNIÓN</h2><p style="text-align:center"><b>Unidad Educativa Eight Academy</b><br>${currentAct.number}</p>`+sectionNames.map(k=>{let title={general:"Información general",antecedentes:"Antecedentes",temas:"Temas tratados",evidencias:"Evidencias presentadas",acuerdos:"Acuerdos alcanzados",compromisos:"Compromisos",observaciones:"Observaciones"}[k];return `<div class="sectionbox ${sectionApproval[k]?"approved":""}" id="sec_${k}"><h4>${title} <span class="tag blue">✨ ACTA AI</span></h4><div class="seccontent" contenteditable="false">${currentAct.sections[k]}</div><div class="section-toolbar"><button class="secondary" onclick="editSection('${k}')">Editar</button><button class="secondary" onclick="approveSection('${k}')">${sectionApproval[k]?"Aprobado ✓":"Aprobar"}</button></div></div>`}).join("");renderReview()}
window.editSection=k=>{let el=$("sec_"+k),c=el.querySelector(".seccontent");c.contentEditable="true";el.classList.add("editing");c.focus();c.onblur=()=>{currentAct.sections[k]=c.innerHTML;c.contentEditable="false";el.classList.remove("editing");toast("Sección actualizada")}}
window.approveSection=k=>{sectionApproval[k]=true;renderAct();toast("Sección aprobada")}
function renderReview(){let done=Object.values(sectionApproval).filter(Boolean).length,p=Math.round(done/sectionNames.length*100);$("reviewProgress").style.width=p+"%";$("reviewPercent").textContent=p+"%";$("sectionReview").innerHTML=sectionNames.map(k=>`<div class="ai-card"><h4>${k}</h4><p>${sectionApproval[k]?'<span class="tag green">Aprobada</span>':'<span class="tag amber">Pendiente</span>'}</p></div>`).join("");$("goSignBtn").disabled=p<100}
$("toggleCompare").onclick=()=>{$("transcriptOriginal").classList.toggle("hidden");$("actDocument").classList.toggle("hidden");$("toggleCompare").textContent=$("transcriptOriginal").classList.contains("hidden")?"Ver transcripción original":"Volver al acta";$("transcriptOriginal").innerHTML="<h3>Conversación original</h3>"+transcript.map(x=>`<p><b>${x.name} (${x.role}):</b> ${x.text}</p>`).join("")}
$("tabAct").onclick=()=>{$("actDocument").classList.remove("hidden");$("transcriptOriginal").classList.add("hidden")};$("tabTranscript").onclick=()=>{$("actDocument").classList.add("hidden");$("transcriptOriginal").classList.remove("hidden");$("transcriptOriginal").innerHTML="<h3>Conversación original</h3>"+transcript.map(x=>`<p><b>${x.name}:</b> ${x.text}</p>`).join("")}
$("goSignBtn").onclick=()=>openSignModal();

function openSignModal(){openModal("Firma del acta",`<div class="signature-grid"><div><h4>Docente — Anita Parreño</h4><canvas id="signTeacher"></canvas><label class="small"><input id="confirmTeacher" type="checkbox"> Confirmo que he revisado el contenido del acta.</label></div><div><h4>Representante — Carolina Pérez</h4><canvas id="signGuardian"></canvas><label class="small"><input id="confirmGuardian" type="checkbox"> Confirmo que he revisado el contenido del acta.</label></div></div>`,"Firmar y cerrar acta",()=>{if(!$("confirmTeacher").checked||!$("confirmGuardian").checked){toast("Ambas partes deben confirmar la revisión");return}finalizeAct()});setTimeout(()=>{setupCanvas("signTeacher");setupCanvas("signGuardian")},50)}
function setupCanvas(id){let c=$(id),ctx=c.getContext("2d"),down=false;let r=c.getBoundingClientRect();c.width=r.width*devicePixelRatio;c.height=180*devicePixelRatio;ctx.scale(devicePixelRatio,devicePixelRatio);ctx.lineWidth=2;ctx.lineCap="round";ctx.strokeStyle="#172033";let pos=e=>{let q=c.getBoundingClientRect();return[e.clientX-q.left,e.clientY-q.top]};c.onpointerdown=e=>{down=true;let[x,y]=pos(e);ctx.beginPath();ctx.moveTo(x,y)};c.onpointermove=e=>{if(!down)return;let[x,y]=pos(e);ctx.lineTo(x,y);ctx.stroke()};c.onpointerup=()=>down=false;c.onpointerleave=()=>down=false}
function finalizeAct(){let m=getMeeting(currentAct.meetingId);m.status="archived";db.acts.push({id:"a"+(db.acts.length+1),meetingId:m.id,number:currentAct.number,status:"archived",date:m.date,html:currentAct.sections});db.audit.push(["09:36","Acta archivada "+currentAct.number]);save();showSuccess()}
function showSuccess(){closeModal();$("actWorkspace").innerHTML=`<div class="success panel"><div class="check">✓</div><h2>Acta completada</h2><p>El acta ha sido revisada y firmada correctamente.</p><p><b>${currentAct.number}</b><br>13 agosto 2026</p><div><button class="secondary" onclick="viewCurrentAct()">Ver acta</button> <button class="secondary" onclick="downloadCurrentAct()">Descargar PDF</button> <button class="secondary" onclick="emailCurrentAct()">Enviar por correo</button> <button class="secondary" onclick="showView('followups')">Crear seguimiento</button> <button class="primary" onclick="showView('dashboard')">Volver al inicio</button></div></div>`;toast("Acta archivada")}
window.viewCurrentAct=()=>openModal("Acta "+currentAct.number,$("actDocument")?.innerHTML||"Acta archivada");
window.downloadCurrentAct=()=>{let blob=new Blob([`ACTA PRO\n${currentAct.number}\n\n`+Object.entries(currentAct.sections).map(([k,v])=>k.toUpperCase()+"\n"+v.replace(/<br>/g,"\n")).join("\n\n")],{type:"text/plain"});let a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=currentAct.number+".txt";a.click();URL.revokeObjectURL(a.href);toast("Descarga generada (MVP)")}
window.emailCurrentAct=()=>toast("Copia enviada al representante (simulación Gmail)");
