function renderCommitments(){$("commitmentTable").innerHTML=db.commitments.map(c=>`<tr><td>${c.responsibleName}</td><td>${c.description}</td><td>${c.dueDate}</td><td>${c.status}</td><td><button class="secondary" onclick="toggleCommitment('${c.id}')">${c.status==="completed"?"Reabrir":"Completar"}</button></td></tr>`).join("")}
window.toggleCommitment=id=>{let c=db.commitments.find(x=>x.id===id);c.status=c.status==="completed"?"pending":"completed";save();renderCommitments();toast("Compromiso actualizado")}
$("addCommitmentBtn").onclick=()=>openModal("Agregar compromiso",`<div class="formgrid"><label>Responsable<input id="coResp" value="Sofía Martínez"></label><label>Fecha<input id="coDate" type="date" value="2026-08-27"></label><label class="wide">Compromiso<textarea id="coDesc" rows="3">Revisar agenda diariamente</textarea></label></div>`,"Agregar",()=>{db.commitments.push({id:"c"+(db.commitments.length+1),meetingId:currentMeetingId,responsibleName:$("coResp").value,description:$("coDesc").value,dueDate:$("coDate").value,status:"pending"});save();renderCommitments();toast("Compromiso agregado")})

function renderFollowups(){$("followupList").innerHTML=db.followups.map(f=>{let s=getStudent(f.studentId),c=db.commitments.find(x=>x.id===f.commitmentId);return `<div class="follow-card"><div><b>${s.name}</b><p class="small">${c?.description||"Seguimiento"}<br>Revisión: ${f.date}</p></div><div>${f.status==="completed"?'<span class="tag green">Completado</span>':'<span class="tag amber">Pendiente</span>'} <button class="secondary" onclick="registerFollowup('${f.id}')">Registrar seguimiento</button></div></div>`}).join("")}
window.registerFollowup=id=>openModal("Registrar seguimiento",`<div class="formgrid"><label class="wide">Observación<textarea id="fuObs" rows="4">Se revisan avances y cumplimiento del compromiso.</textarea></label></div>`,"Guardar",()=>{let f=db.followups.find(x=>x.id===id);f.status="completed";save();renderFollowups();toast("Seguimiento registrado")})

function renderStudents(){let q=($("studentSearch")?.value||"").toLowerCase();$("studentList").innerHTML=db.students.filter(s=>s.name.toLowerCase().includes(q)).map(s=>{let ms=db.meetings.filter(m=>m.studentId===s.id),acs=db.acts.filter(a=>ms.some(m=>m.id===a.meetingId)),cs=db.commitments.filter(c=>ms.some(m=>m.id===c.meetingId)&&c.status!=="completed"),fs=db.followups.filter(f=>f.studentId===s.id&&f.status!=="completed");return `<div class="card"><div class="student-head"><div class="bigavatar">${initials(s.name)}</div><div><h3>${s.name}</h3><p class="small">${s.course} · ${s.code}</p></div></div><div class="grid four" style="margin-top:12px"><div><b>${ms.length}</b><small> Reuniones</small></div><div><b>${acs.length}</b><small> Actas</small></div><div><b>${cs.length}</b><small> Compromisos</small></div><div><b>${fs.length}</b><small> Seguimientos</small></div></div><button class="secondary full" onclick="studentProfile('${s.id}')">Ver historial</button></div>`}).join("")}
$("studentSearch").oninput=renderStudents;
window.studentProfile=id=>{let s=getStudent(id),ms=db.meetings.filter(m=>m.studentId===id);openModal(s.name,`<p><b>${s.course}</b> · ${s.code}</p><div class="timeline">${ms.map(m=>`<div><b>${m.date}</b> — ${m.title}<br><span class="small muted">${m.reason}</span></div>`).join("")}</div>`)}

function renderGuardians(){let q=($("guardianSearch")?.value||"").toLowerCase();$("guardianList").innerHTML=db.guardians.filter(g=>g.name.toLowerCase().includes(q)).map(g=>{let s=getStudent(g.studentId);return `<div class="card"><div class="student-head"><div class="bigavatar">${initials(g.name)}</div><div><h3>${g.name}</h3><p class="small">${g.relation} de ${s.name}</p></div></div><p class="small">${g.email}<br>${g.phone}</p></div>`}).join("")}
$("guardianSearch").oninput=renderGuardians;
