function renderAnalytics(){
  const meetingsEl=$("chartMeetings"), reasonsEl=$("chartReasons");
  if(meetingsEl){const vals=[14,18,16,22,25,19,14,20];meetingsEl.innerHTML=vals.map(v=>`<div class="bar" style="height:${v*5}px"><b>${v}</b></div>`).join("");}
  if(reasonsEl){const vals=[28,22,18,16,12,9];reasonsEl.innerHTML=vals.map(v=>`<div class="bar" style="height:${v*5}px;background:#dff1eb"><b>${v}</b></div>`).join("");}
}
function renderArchive(){const list=$("archiveList");if(!list)return;const q=($("archiveSearch")?.value||"").toLowerCase(),f=$("archiveStatus")?.value||"all";list.innerHTML=db.acts.filter(a=>f==="all"||a.status===f).filter(a=>{const m=getMeeting(a.meetingId);if(!m)return false;const s=getStudent(m.studentId),g=getGuardian(m.guardianId);return `${s?.name||""} ${g?.name||""} ${m.type||""} ${a.number||""}`.toLowerCase().includes(q)}).map(a=>{const m=getMeeting(a.meetingId),s=getStudent(m.studentId);return `<div class="repo-row"><div><b>${s?.name||"Estudiante"}</b><div class="small muted">${a.date} · ${m.type} · ${a.number}</div></div><div class="repo-actions">${statusTag(a.status)}<button class="secondary" onclick="viewArchive('${a.id}')">Ver</button></div></div>`}).join("")||`<div class="panel muted small">No se encontraron actas con esos filtros.</div>`}
window.viewArchive=id=>{const a=db.acts.find(x=>x.id===id);if(!a)return;const m=getMeeting(a.meetingId),s=getStudent(m.studentId),g=getGuardian(m.guardianId);openModal(a.number,`<p><b>${s?.name||"Estudiante"}</b><br>${m?.reason||""}<br>${a.date}</p><p>Representante: ${g?.name||"—"}<br>Estado: ${a.status}</p>`)};
function renderNotifications(){const list=$("notificationList");if(list)list.innerHTML=db.notifications.map(n=>`<div class="notif" style="${n.read?"opacity:.55":""}"><div class="nicon">🔔</div><div><b>${n.text}</b><div class="small muted">${n.read?"Leída":"Nueva"}</div></div></div>`).join("")}
function renderAudit(){const el=$("auditTimeline");if(el)el.innerHTML=db.audit.map(a=>`<div class="audit-row"><time>${a[0]}</time><div>${a[1]}</div></div>`).join("")}
function bindSecondaryUX(){if($("archiveSearch"))$("archiveSearch").oninput=renderArchive;if($("archiveStatus"))$("archiveStatus").onchange=renderArchive;if($("markAllRead"))$("markAllRead").onclick=()=>{db.notifications.forEach(n=>n.read=true);save();renderNotifications();toast("Notificaciones marcadas como leídas")};const sync=()=>{const el=$("syncResult");if(el)el.textContent="Buscando nuevas reuniones…";setTimeout(()=>{if(el)el.textContent="2 reuniones nuevas encontradas.";toast("Calendario sincronizado")},900)};if($("syncCalendar"))$("syncCalendar").onclick=sync;if($("syncCalendar2"))$("syncCalendar2").onclick=sync}
function renderAll(){renderDashboard();renderMeetings();fillMeetingForm();renderCommitments();renderFollowups();renderStudents();renderGuardians();renderAnalytics();renderArchive();renderNotifications();renderAudit();applyRole()}
function loadSpeech67(){if(!document.querySelector('link[href="speech-v67.css"]')){const l=document.createElement('link');l.rel='stylesheet';l.href='speech-v67.css';document.head.appendChild(l)}if(!document.querySelector('script[src="speech-v67a.js"]')){const s=document.createElement('script');s.src='speech-v67a.js';document.body.appendChild(s)}}
function actNarrative(){const g=transcript.filter(x=>/madre|padre|representante/i.test(x.role)),t=transcript.filter(x=>/docente/i.test(x.role)),s=transcript.filter(x=>/estudiante/i.test(x.role));const topics=[];if(transcript.some(x=>/agenda|organiza|tarea|actividad/i.test(x.text)))topics.push('organización académica y cumplimiento de actividades');if(transcript.some(x=>/tiempo|demora|distra/i.test(x.text)))topics.push('gestión del tiempo y continuidad en las tareas');if(!topics.length)topics.push('situaciones expuestas durante la reunión');const d=[];if(g.length)d.push('La persona representante expuso sus observaciones y manifestó interés en fortalecer el acompañamiento desde el hogar.');if(t.length)d.push('La docente presentó observaciones relacionadas con el desarrollo de las actividades escolares y planteó acciones de seguimiento.');if(s.length)d.push('La estudiante participó en el encuentro y manifestó aspectos relacionados con su organización y ejecución de las actividades asignadas.');return{a:'La reunión se desarrolló con el propósito de revisar la situación planteada y establecer acciones de acompañamiento, manteniendo un registro objetivo de los aspectos tratados.',t:'Durante el encuentro se abordaron principalmente '+topics.join(', ')+'. '+d.join(' '),o:'Las partes expresaron su disposición para dar cumplimiento a los acuerdos establecidos y realizar el seguimiento correspondiente.'}}
function professionalBuildAct(){const m=getMeeting(currentMeetingId),s=getStudent(m.studentId),g=getGuardian(m.guardianId),t=getTeacher(m.teacherId),n=actNarrative(),ev=evidence.length?evidence.map(e=>`<b>${e.title}</b> — ${e.desc}`).join('<br>'):'No se registraron evidencias adicionales durante la reunión.',cs=db.commitments.filter(c=>c.meetingId===currentMeetingId),com=cs.length?cs.map(c=>`<b>${c.responsibleName}</b>: ${c.description}. Fecha prevista: ${c.dueDate}.`).join('<br>'):'No se registraron compromisos con fecha definida durante la reunión.';currentAct={meetingId:m.id,number:'ACTA-2026-'+String(184+db.acts.length).padStart(5,'0'),sections:{general:`Fecha: ${m.date}<br>Hora: ${m.startTime}<br>Docente: ${t.name}<br>Estudiante: ${s.name}<br>Representante: ${g.name}<br>Curso: ${s.course}<br>Motivo: ${m.reason}`,antecedentes:n.a,temas:n.t,evidencias:ev,acuerdos:com,compromisos:com,observaciones:n.o}};sectionApproval=Object.fromEntries(sectionNames.map(x=>[x,false]))}
function professionalRenderAct(){if(!currentAct)return;const s=currentAct.sections,h=$("actDocument");h.innerHTML=`<div class="pro-act-head"><h2>ACTA DE REUNIÓN CON REPRESENTANTE</h2><p>Unidad Educativa Eight Academy · ${currentAct.number}</p></div><div class="pro-block"><h4>Información general <span class="pro-label">Institucional</span></h4><div class="pro-text" contenteditable="true" data-k="general">${s.general}</div></div><div class="pro-block"><h4>Antecedentes y motivo <span class="pro-label">ACTA AI</span></h4><div class="pro-text" contenteditable="true" data-k="antecedentes">${s.antecedentes}</div></div><div class="pro-block"><h4>Desarrollo de la reunión <span class="pro-label">ACTA AI</span></h4><div class="pro-text" contenteditable="true" data-k="temas">${s.temas}</div></div><div class="pro-block"><h4>Evidencias mencionadas <span class="pro-label">Trazabilidad</span></h4><div class="pro-text" contenteditable="true" data-k="evidencias">${s.evidencias}</div></div><div class="pro-block"><h4>Acuerdos y compromisos <span class="pro-label">Seguimiento</span></h4><div class="pro-text" contenteditable="true" data-k="acuerdos">${s.acuerdos}</div></div><div class="pro-block"><h4>Observaciones finales <span class="pro-label">ACTA AI</span></h4><div class="pro-text" contenteditable="true" data-k="observaciones">${s.observaciones}</div></div><div class="professional-note">ACTA AI estructura la redacción. El docente verifica hechos, responsables, fechas y acuerdos antes de firmar.</div>`;h.querySelectorAll('[data-k]').forEach(el=>el.oninput=()=>currentAct.sections[el.dataset.k]=el.innerHTML);simpleApproval()}
function simpleApproval(){const aside=$("actWorkspace")?.querySelector('aside.panel');if(!aside||$("simpleReview68"))return;const box=document.createElement('div');box.id='simpleReview68';box.className='simple-review-actions';box.innerHTML='<div class="review-summary">Edita directamente el acta si es necesario. Cuando el contenido sea correcto, aprueba el documento completo.</div><button id="approveWhole68" class="primary full">Aprobar acta y continuar a firma</button>';aside.appendChild(box);$("approveWhole68").onclick=()=>{sectionNames.forEach(k=>sectionApproval[k]=true);renderReview();toast("Acta aprobada por el docente");$("goSignBtn").click()}}
buildAct=professionalBuildAct;renderAct=professionalRenderAct;
bindSecondaryUX();renderAll();loadSpeech67();setTimeout(simpleApproval,500);

/* ACTA FINAL V6.9: firmas persistentes + vista/descarga desde Archivo */
(()=>{
 const E=s=>String(s??'').replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
 const TXT=s=>String(s||'').replace(/<br\s*\/?>/gi,'\n').replace(/<[^>]+>/g,'').trim();
 function dataFor(a){const m=getMeeting(a.meetingId),s=m&&getStudent(m.studentId),g=m&&getGuardian(m.guardianId),t=m&&getTeacher(m.teacherId),h=a.html||{};return{m,s,g,t,h}}
 function sheet(a){const d=dataFor(a),sig=a.signatures||{},agreements=TXT(d.h.acuerdos||d.h.compromisos||'—').split(/\n+/).filter(Boolean);return `<div style="font-family:Times New Roman,serif;background:#fff;color:#111;padding:24px;max-width:760px;margin:auto"><div style="text-align:center;color:#759d89;font:12px Arial">Eight Academy</div><div style="text-align:center;font-weight:700;font-size:17px">UNIDAD EDUCATIVA PARTICULAR “EIGHT ACADEMY”</div><div style="text-align:center;font-weight:700">AÑO LECTIVO 2025 – 2026</div><div style="text-align:center;font-weight:700;font-size:18px;margin:14px 0">ACTA REUNIÓN REPRESENTANTES</div><div style="display:grid;grid-template-columns:1fr .6fr;gap:18px;margin:8px 0"><div><b>Fecha:</b> ${E(d.m?.date||a.date||'—')}</div><div><b>Hora:</b> ${E(d.m?.startTime||'—')}</div></div><div style="display:grid;grid-template-columns:2fr .8fr .6fr;gap:12px"><div><b>Nombre del estudiante:</b> ${E(d.s?.name||'—')}</div><div><b>Grado:</b> ${E(d.s?.course||'—')}</div><div><b>Paralelo:</b> —</div></div><h4>Nombres de los que asisten a la reunión</h4><div>1. ${E(d.g?.name||'Representante')}</div><div>2. ${E(d.s?.name||'Estudiante')}</div><div>3. ${E(d.t?.name||'Docente')}</div><h4>Motivo de la reunión:</h4><div style="line-height:1.6;min-height:90px">${E(TXT(d.h.temas||d.h.antecedentes||d.m?.reason||'—'))}</div><h4>Acuerdos y compromisos:</h4><div style="line-height:1.7;min-height:80px">${(agreements.length?agreements:['—']).map(x=>'✓ '+E(x)).join('<br>')}</div><h4>Firmas de asistentes:</h4><table style="width:100%;border-collapse:collapse"><tr><th style="text-align:left">Nombres</th><th style="text-align:left">Cargo</th><th style="text-align:left">Firma</th></tr><tr><td>${E(d.t?.name||sig.teacherName||'Docente')}</td><td>Docente</td><td>${sig.teacher?`<img src="${sig.teacher}" style="max-width:170px;max-height:58px">`:'Firma registrada'}</td></tr><tr><td>${E(d.g?.name||sig.guardianName||'Representante')}</td><td>${E(d.g?.relation||'Representante')}</td><td>${sig.guardian?`<img src="${sig.guardian}" style="max-width:170px;max-height:58px">`:'Firma registrada'}</td></tr></table><div style="text-align:right;color:#7a8492;font:11px Arial;margin-top:16px">${E(a.number)} · Evidencia institucional archivada</div></div>`}
 window.openSignModal=function(){const m=getMeeting(currentAct?.meetingId||currentMeetingId),g=m&&getGuardian(m.guardianId),t=m&&getTeacher(m.teacherId);openModal('Firma del acta',`<div class="signature-grid"><div><h4>Docente — ${E(t?.name||'Docente')}</h4><canvas id="signTeacher"></canvas><label class="small"><input id="confirmTeacher" type="checkbox"> Confirmo que he revisado el contenido del acta.</label></div><div><h4>Representante — ${E(g?.name||'Representante')}</h4><canvas id="signGuardian"></canvas><label class="small"><input id="confirmGuardian" type="checkbox"> Confirmo que he revisado el contenido del acta.</label></div></div>`,'Firmar y cerrar acta',()=>{if(!$("confirmTeacher").checked||!$("confirmGuardian").checked){toast('Ambas partes deben confirmar la revisión');return}window.finalizeAct()});setTimeout(()=>{setupCanvas('signTeacher');setupCanvas('signGuardian')},50)};
 window.finalizeAct=function(){const m=getMeeting(currentAct.meetingId),g=getGuardian(m.guardianId),t=getTeacher(m.teacherId),tc=$('signTeacher'),gc=$('signGuardian');m.status='archived';const signatures={teacher:tc?.toDataURL('image/png')||'',guardian:gc?.toDataURL('image/png')||'',teacherName:t?.name||'',guardianName:g?.name||'',signedAt:new Date().toISOString()};const existing=db.acts.find(a=>a.meetingId===m.id&&a.number===currentAct.number),rec={id:existing?.id||('a'+(db.acts.length+1)),meetingId:m.id,number:currentAct.number,status:'archived',date:m.date,html:currentAct.sections,signatures};if(existing)Object.assign(existing,rec);else db.acts.push(rec);db.audit.push(['09:36','Acta firmada y archivada '+currentAct.number]);save();showSuccess();setTimeout(()=>renderArchive(),100)};
 window.downloadArchivedAct=id=>{const a=db.acts.find(x=>x.id===id);if(!a)return;const w=window.open('','_blank');if(!w){toast('Permite ventanas emergentes para descargar el acta');return}w.document.write(`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${E(a.number)}</title><style>@page{size:A4;margin:15mm}body{margin:0;background:#fff}table td,table th{padding:8px 5px;border-bottom:1px dotted #333;vertical-align:middle}@media print{button{display:none}}</style></head><body>${sheet(a)}<script>setTimeout(()=>window.print(),300)<\/script></body></html>`);w.document.close()};
 window.viewArchive=id=>{const a=db.acts.find(x=>x.id===id);if(!a)return;openModal('Acta final · '+a.number,`${sheet(a)}<div style="text-align:center;margin-top:14px"><button class="primary" onclick="downloadArchivedAct('${id}')">Descargar PDF</button></div>`)};
 window.downloadCurrentAct=()=>{const a=db.acts.find(x=>x.number===currentAct?.number);if(a)downloadArchivedAct(a.id);else toast('Firma el acta para generar la versión final')};
 window.viewCurrentAct=()=>{const a=db.acts.find(x=>x.number===currentAct?.number);if(a)viewArchive(a.id);else toast('Firma el acta para generar la versión final')};
 renderArchive=function(){const list=$("archiveList");if(!list)return;const q=($("archiveSearch")?.value||"").toLowerCase(),f=$("archiveStatus")?.value||"all";list.innerHTML=db.acts.filter(a=>f==="all"||a.status===f).filter(a=>{const m=getMeeting(a.meetingId);if(!m)return false;const s=getStudent(m.studentId),g=getGuardian(m.guardianId);return `${s?.name||""} ${g?.name||""} ${m.type||""} ${a.number||""}`.toLowerCase().includes(q)}).map(a=>{const m=getMeeting(a.meetingId),s=getStudent(m.studentId);return `<div class="repo-row"><div><b>${E(s?.name||'Estudiante')}</b><div class="small muted">${E(a.date)} · ${E(m.type)} · ${E(a.number)}</div></div><div class="repo-actions">${statusTag(a.status)}<button class="secondary" onclick="viewArchive('${a.id}')">Ver acta</button><button class="primary" onclick="downloadArchivedAct('${a.id}')">Descargar PDF</button></div></div>`}).join('')||'<div class="panel muted small">No se encontraron actas con esos filtros.</div>'};
 if($("archiveSearch"))$("archiveSearch").oninput=renderArchive;if($("archiveStatus"))$("archiveStatus").onchange=renderArchive;if($("goSignBtn"))$("goSignBtn").onclick=()=>openSignModal();renderArchive();
})();